/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package fresto.data;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class EntryOperationCallEdge implements org.apache.thrift.TBase<EntryOperationCallEdge, EntryOperationCallEdge._Fields>, java.io.Serializable, Cloneable, Comparable<EntryOperationCallEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("EntryOperationCallEdge");

  private static final org.apache.thrift.protocol.TField RESOURCE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("resourceId", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField OPERATION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("OperationId", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField LOCAL_HOST_FIELD_DESC = new org.apache.thrift.protocol.TField("localHost", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField LOCAL_PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("localPort", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField CONTEXT_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("contextPath", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField SERVLET_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("servletPath", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField HTTP_METHOD_FIELD_DESC = new org.apache.thrift.protocol.TField("httpMethod", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField UUID_FIELD_DESC = new org.apache.thrift.protocol.TField("uuid", org.apache.thrift.protocol.TType.STRING, (short)9);
  private static final org.apache.thrift.protocol.TField SEQUENCE_FIELD_DESC = new org.apache.thrift.protocol.TField("sequence", org.apache.thrift.protocol.TType.I32, (short)10);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EntryOperationCallEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EntryOperationCallEdgeTupleSchemeFactory());
  }

  public ResourceID resourceId; // required
  public OperationID OperationId; // required
  public String localHost; // required
  public int localPort; // required
  public String contextPath; // required
  public String servletPath; // required
  public String httpMethod; // required
  public long timestamp; // required
  public String uuid; // required
  public int sequence; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESOURCE_ID((short)1, "resourceId"),
    OPERATION_ID((short)2, "OperationId"),
    LOCAL_HOST((short)3, "localHost"),
    LOCAL_PORT((short)4, "localPort"),
    CONTEXT_PATH((short)5, "contextPath"),
    SERVLET_PATH((short)6, "servletPath"),
    HTTP_METHOD((short)7, "httpMethod"),
    TIMESTAMP((short)8, "timestamp"),
    UUID((short)9, "uuid"),
    SEQUENCE((short)10, "sequence");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESOURCE_ID
          return RESOURCE_ID;
        case 2: // OPERATION_ID
          return OPERATION_ID;
        case 3: // LOCAL_HOST
          return LOCAL_HOST;
        case 4: // LOCAL_PORT
          return LOCAL_PORT;
        case 5: // CONTEXT_PATH
          return CONTEXT_PATH;
        case 6: // SERVLET_PATH
          return SERVLET_PATH;
        case 7: // HTTP_METHOD
          return HTTP_METHOD;
        case 8: // TIMESTAMP
          return TIMESTAMP;
        case 9: // UUID
          return UUID;
        case 10: // SEQUENCE
          return SEQUENCE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LOCALPORT_ISSET_ID = 0;
  private static final int __TIMESTAMP_ISSET_ID = 1;
  private static final int __SEQUENCE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESOURCE_ID, new org.apache.thrift.meta_data.FieldMetaData("resourceId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ResourceID.class)));
    tmpMap.put(_Fields.OPERATION_ID, new org.apache.thrift.meta_data.FieldMetaData("OperationId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, OperationID.class)));
    tmpMap.put(_Fields.LOCAL_HOST, new org.apache.thrift.meta_data.FieldMetaData("localHost", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LOCAL_PORT, new org.apache.thrift.meta_data.FieldMetaData("localPort", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CONTEXT_PATH, new org.apache.thrift.meta_data.FieldMetaData("contextPath", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SERVLET_PATH, new org.apache.thrift.meta_data.FieldMetaData("servletPath", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.HTTP_METHOD, new org.apache.thrift.meta_data.FieldMetaData("httpMethod", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.UUID, new org.apache.thrift.meta_data.FieldMetaData("uuid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SEQUENCE, new org.apache.thrift.meta_data.FieldMetaData("sequence", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(EntryOperationCallEdge.class, metaDataMap);
  }

  public EntryOperationCallEdge() {
    this.sequence = 0;

  }

  public EntryOperationCallEdge(
    ResourceID resourceId,
    OperationID OperationId,
    String localHost,
    int localPort,
    String contextPath,
    String servletPath,
    String httpMethod,
    long timestamp,
    String uuid,
    int sequence)
  {
    this();
    this.resourceId = resourceId;
    this.OperationId = OperationId;
    this.localHost = localHost;
    this.localPort = localPort;
    setLocalPortIsSet(true);
    this.contextPath = contextPath;
    this.servletPath = servletPath;
    this.httpMethod = httpMethod;
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    this.uuid = uuid;
    this.sequence = sequence;
    setSequenceIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EntryOperationCallEdge(EntryOperationCallEdge other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetResourceId()) {
      this.resourceId = new ResourceID(other.resourceId);
    }
    if (other.isSetOperationId()) {
      this.OperationId = new OperationID(other.OperationId);
    }
    if (other.isSetLocalHost()) {
      this.localHost = other.localHost;
    }
    this.localPort = other.localPort;
    if (other.isSetContextPath()) {
      this.contextPath = other.contextPath;
    }
    if (other.isSetServletPath()) {
      this.servletPath = other.servletPath;
    }
    if (other.isSetHttpMethod()) {
      this.httpMethod = other.httpMethod;
    }
    this.timestamp = other.timestamp;
    if (other.isSetUuid()) {
      this.uuid = other.uuid;
    }
    this.sequence = other.sequence;
  }

  public EntryOperationCallEdge deepCopy() {
    return new EntryOperationCallEdge(this);
  }

  @Override
  public void clear() {
    this.resourceId = null;
    this.OperationId = null;
    this.localHost = null;
    setLocalPortIsSet(false);
    this.localPort = 0;
    this.contextPath = null;
    this.servletPath = null;
    this.httpMethod = null;
    setTimestampIsSet(false);
    this.timestamp = 0;
    this.uuid = null;
    this.sequence = 0;

  }

  public ResourceID getResourceId() {
    return this.resourceId;
  }

  public EntryOperationCallEdge setResourceId(ResourceID resourceId) {
    this.resourceId = resourceId;
    return this;
  }

  public void unsetResourceId() {
    this.resourceId = null;
  }

  /** Returns true if field resourceId is set (has been assigned a value) and false otherwise */
  public boolean isSetResourceId() {
    return this.resourceId != null;
  }

  public void setResourceIdIsSet(boolean value) {
    if (!value) {
      this.resourceId = null;
    }
  }

  public OperationID getOperationId() {
    return this.OperationId;
  }

  public EntryOperationCallEdge setOperationId(OperationID OperationId) {
    this.OperationId = OperationId;
    return this;
  }

  public void unsetOperationId() {
    this.OperationId = null;
  }

  /** Returns true if field OperationId is set (has been assigned a value) and false otherwise */
  public boolean isSetOperationId() {
    return this.OperationId != null;
  }

  public void setOperationIdIsSet(boolean value) {
    if (!value) {
      this.OperationId = null;
    }
  }

  public String getLocalHost() {
    return this.localHost;
  }

  public EntryOperationCallEdge setLocalHost(String localHost) {
    this.localHost = localHost;
    return this;
  }

  public void unsetLocalHost() {
    this.localHost = null;
  }

  /** Returns true if field localHost is set (has been assigned a value) and false otherwise */
  public boolean isSetLocalHost() {
    return this.localHost != null;
  }

  public void setLocalHostIsSet(boolean value) {
    if (!value) {
      this.localHost = null;
    }
  }

  public int getLocalPort() {
    return this.localPort;
  }

  public EntryOperationCallEdge setLocalPort(int localPort) {
    this.localPort = localPort;
    setLocalPortIsSet(true);
    return this;
  }

  public void unsetLocalPort() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LOCALPORT_ISSET_ID);
  }

  /** Returns true if field localPort is set (has been assigned a value) and false otherwise */
  public boolean isSetLocalPort() {
    return EncodingUtils.testBit(__isset_bitfield, __LOCALPORT_ISSET_ID);
  }

  public void setLocalPortIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LOCALPORT_ISSET_ID, value);
  }

  public String getContextPath() {
    return this.contextPath;
  }

  public EntryOperationCallEdge setContextPath(String contextPath) {
    this.contextPath = contextPath;
    return this;
  }

  public void unsetContextPath() {
    this.contextPath = null;
  }

  /** Returns true if field contextPath is set (has been assigned a value) and false otherwise */
  public boolean isSetContextPath() {
    return this.contextPath != null;
  }

  public void setContextPathIsSet(boolean value) {
    if (!value) {
      this.contextPath = null;
    }
  }

  public String getServletPath() {
    return this.servletPath;
  }

  public EntryOperationCallEdge setServletPath(String servletPath) {
    this.servletPath = servletPath;
    return this;
  }

  public void unsetServletPath() {
    this.servletPath = null;
  }

  /** Returns true if field servletPath is set (has been assigned a value) and false otherwise */
  public boolean isSetServletPath() {
    return this.servletPath != null;
  }

  public void setServletPathIsSet(boolean value) {
    if (!value) {
      this.servletPath = null;
    }
  }

  public String getHttpMethod() {
    return this.httpMethod;
  }

  public EntryOperationCallEdge setHttpMethod(String httpMethod) {
    this.httpMethod = httpMethod;
    return this;
  }

  public void unsetHttpMethod() {
    this.httpMethod = null;
  }

  /** Returns true if field httpMethod is set (has been assigned a value) and false otherwise */
  public boolean isSetHttpMethod() {
    return this.httpMethod != null;
  }

  public void setHttpMethodIsSet(boolean value) {
    if (!value) {
      this.httpMethod = null;
    }
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public EntryOperationCallEdge setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public String getUuid() {
    return this.uuid;
  }

  public EntryOperationCallEdge setUuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

  public void unsetUuid() {
    this.uuid = null;
  }

  /** Returns true if field uuid is set (has been assigned a value) and false otherwise */
  public boolean isSetUuid() {
    return this.uuid != null;
  }

  public void setUuidIsSet(boolean value) {
    if (!value) {
      this.uuid = null;
    }
  }

  public int getSequence() {
    return this.sequence;
  }

  public EntryOperationCallEdge setSequence(int sequence) {
    this.sequence = sequence;
    setSequenceIsSet(true);
    return this;
  }

  public void unsetSequence() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SEQUENCE_ISSET_ID);
  }

  /** Returns true if field sequence is set (has been assigned a value) and false otherwise */
  public boolean isSetSequence() {
    return EncodingUtils.testBit(__isset_bitfield, __SEQUENCE_ISSET_ID);
  }

  public void setSequenceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SEQUENCE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESOURCE_ID:
      if (value == null) {
        unsetResourceId();
      } else {
        setResourceId((ResourceID)value);
      }
      break;

    case OPERATION_ID:
      if (value == null) {
        unsetOperationId();
      } else {
        setOperationId((OperationID)value);
      }
      break;

    case LOCAL_HOST:
      if (value == null) {
        unsetLocalHost();
      } else {
        setLocalHost((String)value);
      }
      break;

    case LOCAL_PORT:
      if (value == null) {
        unsetLocalPort();
      } else {
        setLocalPort((Integer)value);
      }
      break;

    case CONTEXT_PATH:
      if (value == null) {
        unsetContextPath();
      } else {
        setContextPath((String)value);
      }
      break;

    case SERVLET_PATH:
      if (value == null) {
        unsetServletPath();
      } else {
        setServletPath((String)value);
      }
      break;

    case HTTP_METHOD:
      if (value == null) {
        unsetHttpMethod();
      } else {
        setHttpMethod((String)value);
      }
      break;

    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((Long)value);
      }
      break;

    case UUID:
      if (value == null) {
        unsetUuid();
      } else {
        setUuid((String)value);
      }
      break;

    case SEQUENCE:
      if (value == null) {
        unsetSequence();
      } else {
        setSequence((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESOURCE_ID:
      return getResourceId();

    case OPERATION_ID:
      return getOperationId();

    case LOCAL_HOST:
      return getLocalHost();

    case LOCAL_PORT:
      return Integer.valueOf(getLocalPort());

    case CONTEXT_PATH:
      return getContextPath();

    case SERVLET_PATH:
      return getServletPath();

    case HTTP_METHOD:
      return getHttpMethod();

    case TIMESTAMP:
      return Long.valueOf(getTimestamp());

    case UUID:
      return getUuid();

    case SEQUENCE:
      return Integer.valueOf(getSequence());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESOURCE_ID:
      return isSetResourceId();
    case OPERATION_ID:
      return isSetOperationId();
    case LOCAL_HOST:
      return isSetLocalHost();
    case LOCAL_PORT:
      return isSetLocalPort();
    case CONTEXT_PATH:
      return isSetContextPath();
    case SERVLET_PATH:
      return isSetServletPath();
    case HTTP_METHOD:
      return isSetHttpMethod();
    case TIMESTAMP:
      return isSetTimestamp();
    case UUID:
      return isSetUuid();
    case SEQUENCE:
      return isSetSequence();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EntryOperationCallEdge)
      return this.equals((EntryOperationCallEdge)that);
    return false;
  }

  public boolean equals(EntryOperationCallEdge that) {
    if (that == null)
      return false;

    boolean this_present_resourceId = true && this.isSetResourceId();
    boolean that_present_resourceId = true && that.isSetResourceId();
    if (this_present_resourceId || that_present_resourceId) {
      if (!(this_present_resourceId && that_present_resourceId))
        return false;
      if (!this.resourceId.equals(that.resourceId))
        return false;
    }

    boolean this_present_OperationId = true && this.isSetOperationId();
    boolean that_present_OperationId = true && that.isSetOperationId();
    if (this_present_OperationId || that_present_OperationId) {
      if (!(this_present_OperationId && that_present_OperationId))
        return false;
      if (!this.OperationId.equals(that.OperationId))
        return false;
    }

    boolean this_present_localHost = true && this.isSetLocalHost();
    boolean that_present_localHost = true && that.isSetLocalHost();
    if (this_present_localHost || that_present_localHost) {
      if (!(this_present_localHost && that_present_localHost))
        return false;
      if (!this.localHost.equals(that.localHost))
        return false;
    }

    boolean this_present_localPort = true;
    boolean that_present_localPort = true;
    if (this_present_localPort || that_present_localPort) {
      if (!(this_present_localPort && that_present_localPort))
        return false;
      if (this.localPort != that.localPort)
        return false;
    }

    boolean this_present_contextPath = true && this.isSetContextPath();
    boolean that_present_contextPath = true && that.isSetContextPath();
    if (this_present_contextPath || that_present_contextPath) {
      if (!(this_present_contextPath && that_present_contextPath))
        return false;
      if (!this.contextPath.equals(that.contextPath))
        return false;
    }

    boolean this_present_servletPath = true && this.isSetServletPath();
    boolean that_present_servletPath = true && that.isSetServletPath();
    if (this_present_servletPath || that_present_servletPath) {
      if (!(this_present_servletPath && that_present_servletPath))
        return false;
      if (!this.servletPath.equals(that.servletPath))
        return false;
    }

    boolean this_present_httpMethod = true && this.isSetHttpMethod();
    boolean that_present_httpMethod = true && that.isSetHttpMethod();
    if (this_present_httpMethod || that_present_httpMethod) {
      if (!(this_present_httpMethod && that_present_httpMethod))
        return false;
      if (!this.httpMethod.equals(that.httpMethod))
        return false;
    }

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    boolean this_present_uuid = true && this.isSetUuid();
    boolean that_present_uuid = true && that.isSetUuid();
    if (this_present_uuid || that_present_uuid) {
      if (!(this_present_uuid && that_present_uuid))
        return false;
      if (!this.uuid.equals(that.uuid))
        return false;
    }

    boolean this_present_sequence = true;
    boolean that_present_sequence = true;
    if (this_present_sequence || that_present_sequence) {
      if (!(this_present_sequence && that_present_sequence))
        return false;
      if (this.sequence != that.sequence)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(EntryOperationCallEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResourceId()).compareTo(other.isSetResourceId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResourceId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resourceId, other.resourceId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperationId()).compareTo(other.isSetOperationId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperationId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.OperationId, other.OperationId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLocalHost()).compareTo(other.isSetLocalHost());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocalHost()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.localHost, other.localHost);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLocalPort()).compareTo(other.isSetLocalPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocalPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.localPort, other.localPort);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetContextPath()).compareTo(other.isSetContextPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetContextPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.contextPath, other.contextPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetServletPath()).compareTo(other.isSetServletPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetServletPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.servletPath, other.servletPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHttpMethod()).compareTo(other.isSetHttpMethod());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHttpMethod()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.httpMethod, other.httpMethod);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUuid()).compareTo(other.isSetUuid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUuid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uuid, other.uuid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSequence()).compareTo(other.isSetSequence());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSequence()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sequence, other.sequence);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("EntryOperationCallEdge(");
    boolean first = true;

    sb.append("resourceId:");
    if (this.resourceId == null) {
      sb.append("null");
    } else {
      sb.append(this.resourceId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("OperationId:");
    if (this.OperationId == null) {
      sb.append("null");
    } else {
      sb.append(this.OperationId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("localHost:");
    if (this.localHost == null) {
      sb.append("null");
    } else {
      sb.append(this.localHost);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("localPort:");
    sb.append(this.localPort);
    first = false;
    if (!first) sb.append(", ");
    sb.append("contextPath:");
    if (this.contextPath == null) {
      sb.append("null");
    } else {
      sb.append(this.contextPath);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("servletPath:");
    if (this.servletPath == null) {
      sb.append("null");
    } else {
      sb.append(this.servletPath);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("httpMethod:");
    if (this.httpMethod == null) {
      sb.append("null");
    } else {
      sb.append(this.httpMethod);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    if (!first) sb.append(", ");
    sb.append("uuid:");
    if (this.uuid == null) {
      sb.append("null");
    } else {
      sb.append(this.uuid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sequence:");
    sb.append(this.sequence);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (resourceId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'resourceId' was not present! Struct: " + toString());
    }
    if (OperationId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'OperationId' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'timestamp' because it's a primitive and you chose the non-beans generator.
    if (uuid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'uuid' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (OperationId != null) {
      OperationId.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EntryOperationCallEdgeStandardSchemeFactory implements SchemeFactory {
    public EntryOperationCallEdgeStandardScheme getScheme() {
      return new EntryOperationCallEdgeStandardScheme();
    }
  }

  private static class EntryOperationCallEdgeStandardScheme extends StandardScheme<EntryOperationCallEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, EntryOperationCallEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESOURCE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.resourceId = new ResourceID();
              struct.resourceId.read(iprot);
              struct.setResourceIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPERATION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.OperationId = new OperationID();
              struct.OperationId.read(iprot);
              struct.setOperationIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // LOCAL_HOST
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.localHost = iprot.readString();
              struct.setLocalHostIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // LOCAL_PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.localPort = iprot.readI32();
              struct.setLocalPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CONTEXT_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.contextPath = iprot.readString();
              struct.setContextPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // SERVLET_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.servletPath = iprot.readString();
              struct.setServletPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // HTTP_METHOD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.httpMethod = iprot.readString();
              struct.setHttpMethodIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // UUID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.uuid = iprot.readString();
              struct.setUuidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // SEQUENCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.sequence = iprot.readI32();
              struct.setSequenceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTimestamp()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestamp' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, EntryOperationCallEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.resourceId != null) {
        oprot.writeFieldBegin(RESOURCE_ID_FIELD_DESC);
        struct.resourceId.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.OperationId != null) {
        oprot.writeFieldBegin(OPERATION_ID_FIELD_DESC);
        struct.OperationId.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.localHost != null) {
        oprot.writeFieldBegin(LOCAL_HOST_FIELD_DESC);
        oprot.writeString(struct.localHost);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LOCAL_PORT_FIELD_DESC);
      oprot.writeI32(struct.localPort);
      oprot.writeFieldEnd();
      if (struct.contextPath != null) {
        oprot.writeFieldBegin(CONTEXT_PATH_FIELD_DESC);
        oprot.writeString(struct.contextPath);
        oprot.writeFieldEnd();
      }
      if (struct.servletPath != null) {
        oprot.writeFieldBegin(SERVLET_PATH_FIELD_DESC);
        oprot.writeString(struct.servletPath);
        oprot.writeFieldEnd();
      }
      if (struct.httpMethod != null) {
        oprot.writeFieldBegin(HTTP_METHOD_FIELD_DESC);
        oprot.writeString(struct.httpMethod);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      if (struct.uuid != null) {
        oprot.writeFieldBegin(UUID_FIELD_DESC);
        oprot.writeString(struct.uuid);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SEQUENCE_FIELD_DESC);
      oprot.writeI32(struct.sequence);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EntryOperationCallEdgeTupleSchemeFactory implements SchemeFactory {
    public EntryOperationCallEdgeTupleScheme getScheme() {
      return new EntryOperationCallEdgeTupleScheme();
    }
  }

  private static class EntryOperationCallEdgeTupleScheme extends TupleScheme<EntryOperationCallEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, EntryOperationCallEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.resourceId.write(oprot);
      struct.OperationId.write(oprot);
      oprot.writeI64(struct.timestamp);
      oprot.writeString(struct.uuid);
      BitSet optionals = new BitSet();
      if (struct.isSetLocalHost()) {
        optionals.set(0);
      }
      if (struct.isSetLocalPort()) {
        optionals.set(1);
      }
      if (struct.isSetContextPath()) {
        optionals.set(2);
      }
      if (struct.isSetServletPath()) {
        optionals.set(3);
      }
      if (struct.isSetHttpMethod()) {
        optionals.set(4);
      }
      if (struct.isSetSequence()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetLocalHost()) {
        oprot.writeString(struct.localHost);
      }
      if (struct.isSetLocalPort()) {
        oprot.writeI32(struct.localPort);
      }
      if (struct.isSetContextPath()) {
        oprot.writeString(struct.contextPath);
      }
      if (struct.isSetServletPath()) {
        oprot.writeString(struct.servletPath);
      }
      if (struct.isSetHttpMethod()) {
        oprot.writeString(struct.httpMethod);
      }
      if (struct.isSetSequence()) {
        oprot.writeI32(struct.sequence);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, EntryOperationCallEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.resourceId = new ResourceID();
      struct.resourceId.read(iprot);
      struct.setResourceIdIsSet(true);
      struct.OperationId = new OperationID();
      struct.OperationId.read(iprot);
      struct.setOperationIdIsSet(true);
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
      struct.uuid = iprot.readString();
      struct.setUuidIsSet(true);
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.localHost = iprot.readString();
        struct.setLocalHostIsSet(true);
      }
      if (incoming.get(1)) {
        struct.localPort = iprot.readI32();
        struct.setLocalPortIsSet(true);
      }
      if (incoming.get(2)) {
        struct.contextPath = iprot.readString();
        struct.setContextPathIsSet(true);
      }
      if (incoming.get(3)) {
        struct.servletPath = iprot.readString();
        struct.setServletPathIsSet(true);
      }
      if (incoming.get(4)) {
        struct.httpMethod = iprot.readString();
        struct.setHttpMethodIsSet(true);
      }
      if (incoming.get(5)) {
        struct.sequence = iprot.readI32();
        struct.setSequenceIsSet(true);
      }
    }
  }

}

